/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiCopilotRouteImport } from './routes/ai-copilot'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as GstInvoicingRouteImport } from './routes/gst-invoicing'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as TelephonyRouteImport } from './routes/telephony'
import { Route as WhatsappInboxRouteImport } from './routes/whatsapp-inbox'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCopilotRoute = AiCopilotRouteImport.update({
  id: '/ai-copilot',
  path: '/ai-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const GstInvoicingRoute = GstInvoicingRouteImport.update({
  id: '/gst-invoicing',
  path: '/gst-invoicing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const TelephonyRoute = TelephonyRouteImport.update({
  id: '/telephony',
  path: '/telephony',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappInboxRoute = WhatsappInboxRouteImport.update({
  id: '/whatsapp-inbox',
  path: '/whatsapp-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/calls': typeof CallsRoute
  '/contacts': typeof ContactsRoute
  '/gst-invoicing': typeof GstInvoicingRoute
  '/integrations': typeof IntegrationsRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/telephony': typeof TelephonyRoute
  '/whatsapp-inbox': typeof WhatsappInboxRoute
  '/workflows': typeof WorkflowsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/calls': typeof CallsRoute
  '/contacts': typeof ContactsRoute
  '/gst-invoicing': typeof GstInvoicingRoute
  '/integrations': typeof IntegrationsRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/telephony': typeof TelephonyRoute
  '/whatsapp-inbox': typeof WhatsappInboxRoute
  '/workflows': typeof WorkflowsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/calls': typeof CallsRoute
  '/contacts': typeof ContactsRoute
  '/gst-invoicing': typeof GstInvoicingRoute
  '/integrations': typeof IntegrationsRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/telephony': typeof TelephonyRoute
  '/whatsapp-inbox': typeof WhatsappInboxRoute
  '/workflows': typeof WorkflowsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-copilot'
    | '/calls'
    | '/contacts'
    | '/gst-invoicing'
    | '/integrations'
    | '/pipeline'
    | '/pricing'
    | '/telephony'
    | '/whatsapp-inbox'
    | '/workflows'
    | '/blog/$slug'
    | '/solutions/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-copilot'
    | '/calls'
    | '/contacts'
    | '/gst-invoicing'
    | '/integrations'
    | '/pipeline'
    | '/pricing'
    | '/telephony'
    | '/whatsapp-inbox'
    | '/workflows'
    | '/blog/$slug'
    | '/solutions/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/ai-copilot'
    | '/calls'
    | '/contacts'
    | '/gst-invoicing'
    | '/integrations'
    | '/pipeline'
    | '/pricing'
    | '/telephony'
    | '/whatsapp-inbox'
    | '/workflows'
    | '/blog/$slug'
    | '/solutions/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCopilotRoute: typeof AiCopilotRoute
  CallsRoute: typeof CallsRoute
  ContactsRoute: typeof ContactsRoute
  GstInvoicingRoute: typeof GstInvoicingRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PipelineRoute: typeof PipelineRoute
  PricingRoute: typeof PricingRoute
  TelephonyRoute: typeof TelephonyRoute
  WhatsappInboxRoute: typeof WhatsappInboxRoute
  WorkflowsRoute: typeof WorkflowsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-copilot': {
      id: '/ai-copilot'
      path: '/ai-copilot'
      fullPath: '/ai-copilot'
      preLoaderRoute: typeof AiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst-invoicing': {
      id: '/gst-invoicing'
      path: '/gst-invoicing'
      fullPath: '/gst-invoicing'
      preLoaderRoute: typeof GstInvoicingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telephony': {
      id: '/telephony'
      path: '/telephony'
      fullPath: '/telephony'
      preLoaderRoute: typeof TelephonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-inbox': {
      id: '/whatsapp-inbox'
      path: '/whatsapp-inbox'
      fullPath: '/whatsapp-inbox'
      preLoaderRoute: typeof WhatsappInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCopilotRoute: AiCopilotRoute,
  CallsRoute: CallsRoute,
  ContactsRoute: ContactsRoute,
  GstInvoicingRoute: GstInvoicingRoute,
  IntegrationsRoute: IntegrationsRoute,
  PipelineRoute: PipelineRoute,
  PricingRoute: PricingRoute,
  TelephonyRoute: TelephonyRoute,
  WhatsappInboxRoute: WhatsappInboxRoute,
  WorkflowsRoute: WorkflowsRoute,
  BlogSlugRoute: BlogSlugRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
